### ISSUE TITLE
error for kingdomsX support

### ISSUE THREAD

**Issue by LobbyTech-MC** [Crazy-Crew/Crazy-Enchantments#543]
error in console:

[13:55:33 ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.8-Dev-Build-v8.1-SNAPSHOT-Build#150
java.lang.NoClassDefFoundError: org/kingdoms/manager/game/GameManagement
        at me.badbones69.premiumhooks.factions.KingdomSupport.isFriendly(KingdomSupport.java:14) ~[?:?]
        at me.badbones69.crazyenchantments.multisupport.Support.isFriendly(Support.java:67) ~[?:?]
        at me.badbones69.crazyenchantments.enchantments.Swords.onPlayerDamage(Swords.java:54) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1320.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-130]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1035) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:922) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:878) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1067) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1823) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1159) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.EntityPlayer.damageEntity(EntityPlayer.java:833) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.EntityHuman.attack(EntityHuman.java:1120) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.EntityPlayer.attack(EntityPlayer.java:1861) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2139) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[13:55:33 WARN]: [CrazyEnchantments] Plugin CrazyEnchantments v1.8-Dev-Build-v8.1-SNAPSHOT-Build#150 generated an exception while executing task 454549
java.lang.NoClassDefFoundError: org/kingdoms/manager/game/GameManagement
        at me.badbones69.premiumhooks.factions.KingdomSupport.isFriendly(KingdomSupport.java:14) ~[?:?]
        at me.badbones69.crazyenchantments.multisupport.Support.isFriendly(Support.java:67) ~[?:?]
        at me.badbones69.crazyenchantments.enchantments.Armor$2.run(Armor.java:114) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-130]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-130]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

**Versions (please complete the following information):**
 - Minecraft Server Version: paper-1.16.1  build130
 - Plugin Version: CrazyEnchantments v1.8-Dev-Build-v8.1-SNAPSHOT-Build#150
- kingdoms-1.7.9

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
