### ISSUE TITLE
Error Spam in console.

### ISSUE THREAD

**Issue by SavagePanda116** [Crazy-Crew/Crazy-Enchantments#589]
We're getting some errors spammed in our console. Here are a few of them that were generated when a player used a shovel that was enchanted with Oxygenate, Hellforged, and Haste:
https://pastebin.com/q10H4TRq
https://pastebin.com/Navsjx7j

It also constantly spams this:
[14:12:40 ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.8-Dev-Build-v9-RELEASE
java.lang.NullPointerException: null

We're using the latest Spigot update of Crazy Enchantments. We have used Jenkins dev builds in the past, and this has been happening since at least the 167 build, I believe. We had been using an old Jenkins version, noticed the errors, then noticed there was an update for the plugin. So, we added the update, hoping that it fixed it, but it hasn't.

Our server is 1.16.5 on Paper build 526.

I'll also attach our latest log in case that is needed or may help.

Thanks!

[latest.log](https://github.com/badbones69/Crazy-Enchantments/files/6312914/latest.log)

**Comment by RyderBelserion** [comment]
The latest build on the jenkins has a fix for this -> https://jenkins.badbones69.com/job/Crazy-Enchantments/

**Comment by taiprovip3** [comment]
excuteme, Author, how can i fix this:
Could not pass event EntityDeathEvent to CrazyEnchantments v1.8-Dev-Build-v9-RELEASE

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0

at me.badbones69.crazyenchantments.api.CrazyEnchantments.hasEnchantment(CrazyEnchantments.java:565) ~[?:?]

at me.badbones69.crazyenchantments.api.CrazyEnchantments.hasEnchantments(CrazyEnchantments.java:547) ~[?:?]

at me.badbones69.crazyenchantments.enchantments.Swords.onEntityDeath(Swords.java:436) ~[?:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor494.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-778]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-778]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-778]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-778]

at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$null$4(EntitiesListener.java:432) ~[?:?]

at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-778]

at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-778]

at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-778]

at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-778]

at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-778]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-778]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]

at java.lang.Thread.run(Unknown Source) [?:?]
