### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by xMrOxy** [Crazy-Crew/Crazy-Enchantments#626]
**Describe the bug**
[23:31:31] [Server thread/ERROR]: Error occurred while enabling CrazyEnchantments v1.8-Dev-Build-v9-RELEASE (Is it up to date?)

java.lang.ClassCastException: class de.dustplanet.silkspawners.SilkSpawners cannot be cast to class de.dustplanet.silkspawners.SilkSpawners (de.dustplanet.silkspawners.SilkSpawners is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2e8a8cd3; de.dustplanet.silkspawners.SilkSpawners is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1564e210)

	at de.dustplanet.util.SilkUtil.hookIntoSilkSpanwers(SilkUtil.java:138) ~[?:?]

	at me.badbones69.premiumhooks.spawners.SilkSpawnerSupport.<init>(SilkSpawnerSupport.java:21) ~[?:?]

	at me.badbones69.crazyenchantments.Main.onEnable(Main.java:94) ~[?:?]

	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-788]

	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-788]

	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-788]

	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-788]

	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-788]

	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-788]

	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-788]

	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-788]

	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]

	at java.lang.Thread.run(Thread.java:834) [?:?]

**Versions (please complete the following information):**
 - Minecraft Server Version: [paper-1.16.5-788]
 - Plugin Version: [1.8-Dev-Build-v9-RELEASE]

**Issue**
Plugin doesn't work

**Comment by RyderBelserion** [comment]
See [`#623`](https://github.com/Crazy-Crew/Crazy-Enchantments/issues/623) for a solution.

Please also update to the latest release. [Click Me](https://github.com/Crazy-Crew/Crazy-Enchantments/releases/tag/v1.8-Dev-Build-v11) - Scroll to the bottom.
