### ISSUE TITLE
Latest version of CE not compatible with latest version of Silk Spawners for Minecraft 1.16.5

### ISSUE THREAD

**Issue by xiaolintangyuan** [Crazy-Crew/Crazy-Enchantments#639]
Unable to enable both CE and Silk Spawners.
java.lang.ClassCastException: class de.dustplanet.silkspawners.SilkSpawners cannot be cast to class de.dustplanet.silkspawners.SilkSpawners (de.dustplanet.silkspawners.SilkSpawners is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @10a0b683; de.dustplanet.silkspawners.SilkSpawners is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @34438d07)
        at de.dustplanet.util.SilkUtil.hookIntoSilkSpanwers(SilkUtil.java:138) ~[?:?]
        at me.badbones69.premiumhooks.spawners.SilkSpawnerSupport.<init>(SilkSpawnerSupport.java:21) ~[?:?]
        at me.badbones69.crazyenchantments.Main.onEnable(Main.java:94) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-792]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.5
 - SilkSpawners: v7.0.0 --1.8 up to 1.16.5--
 - Plugin Version: 1.8-Dev-Build-v10-Build#182

**Issue**
Unable to load plugin due to the exception above.

**Comment by RyderBelserion** [comment]
You have to downgrade SIlkSpawners for now.
