### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by mitchngwen** [Crazy-Crew/Crazy-Enchantments#651]
I need an update for 1.18.2. My server was inadvertently updated to 1.18.2 and now I can not go back to 1.18.1. Have similar issue with CrazyCrates, I'll post the error log over there for that one. If this is an issue with purpur let me know and I'll let them know instead.  Error log below:

[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Enabling CrazyEnchantments v1.8-Dev-Build-v11-Build-#8
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the config.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded config.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the BlockList.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded BlockList.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the Data.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded Data.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the Enchantments.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded Enchantments.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the GKitz.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded GKitz.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the Messages.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded Messages.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the Enchantment-Types.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded Enchantment-Types.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the Signs.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded Signs.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Loading the Tinker.yml
[18:50:20] [Server thread/INFO]: [CrazyEnchantments] Successfully loaded Tinker.yml
[18:50:20] [Server thread/WARN]: [NBTAPI] [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
[18:50:20] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'inventory.CraftItemStack'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftItemStack
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:17) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.load(CrazyEnchantments.java:203) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.Main.onEnable(Main.java:37) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:50:20] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'inventory.CraftMetaItem'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftMetaItem
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:18) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.load(CrazyEnchantments.java:203) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.Main.onEnable(Main.java:37) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:50:20] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'entity.CraftEntity'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:19) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.load(CrazyEnchantments.java:203) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.Main.onEnable(Main.java:37) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:50:20] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'CraftWorld'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.CraftWorld
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:20) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.load(CrazyEnchantments.java:203) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.Main.onEnable(Main.java:37) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:50:21] [Server thread/WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'persistence.CraftPersistentDataContainer'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.persistence.CraftPersistentDataContainer
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:21) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.load(CrazyEnchantments.java:203) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.Main.onEnable(Main.java:37) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:50:21] [Server thread/INFO]: [NBTAPI] Unable to find the method 'asNMSCopy' in 'null' Args: [class org.bukkit.inventory.ItemStack] Enum: ITEMSTACK_NMSCOPY
[18:50:21] [Server thread/INFO]: [NBTAPI] Unable to find the method 'asCraftMirror' in 'null' Args: [class net.minecraft.world.item.ItemStack] Enum: ITEMSTACK_BUKKITMIRROR
[18:50:21] [Server thread/INFO]: [NBTAPI] Unable to find the method 'getHandle' in 'null' Args: [] Enum: CRAFT_WORLD_GET_HANDLE
[18:50:21] [Server thread/INFO]: [NBTAPI] Unable to find the method 'getHandle' in 'null' Args: [] Enum: CRAFT_ENTITY_GET_HANDLE
[18:50:21] [Server thread/INFO]: [NBTAPI] Unable to find the method 'toTagCompound' in 'null' Args: [] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_TO_TAG
[18:50:21] [Server thread/INFO]: [NBTAPI] Unable to find the method 'getRaw' in 'null' Args: [] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_GET_MAP
[18:50:21] [Server thread/INFO]: [NBTAPI] Unable to find the method 'putAll' in 'null' Args: [class net.minecraft.nbt.NBTTagCompound] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_PUT_ALL
[18:50:21] [Server thread/ERROR]: Error occurred while enabling CrazyEnchantments v1.8-Dev-Build-v11-Build-#8 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.badbones69.crazyenchantments.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.load(CrazyEnchantments.java:203) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at me.badbones69.crazyenchantments.Main.onEnable(Main.java:37) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredField(String)" because the return value of "me.badbones69.crazyenchantments.nbtapi.utils.nmsmappings.ClassWrapper.getClazz()" is null
	at me.badbones69.crazyenchantments.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:35) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	... 14 more
[18:50:21] [Server thread/INFO]: [CrazyEnchantments] Disabling CrazyEnchantments v1.8-Dev-Build-v11-Build-#8
[18:50:21] [Server thread/ERROR]: Error occurred while disabling CrazyEnchantments v1.8-Dev-Build-v11-Build-#8 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.badbones69.crazyenchantments.enchantments.Armor.stop()" because "this.armor" is null
	at me.badbones69.crazyenchantments.Main.onDisable(Main.java:107) ~[CrazyEnchantments[v1.8-Dev-Build-v11] (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by RyderBelserion** [comment]
Check the jenkins in a bit -> https://jenkins.badbones69.com/job/Crazy-Enchantments/

**Comment by mitchngwen** [comment]
Update*I was going to post a similar bug on CrazyCrates, but it seems that is already fixed. Thank you, thank you, thank you.
