### ISSUE TITLE
[Bug Report] I keep getting these errors

### ISSUE THREAD

**Issue by SysAdminDoc** [Crazy-Crew/Crazy-Enchantments#657]
! [Wed 18:52:29 WARN  CrazyEnchantments] Task #7633 for CrazyEnchantments v1.8-Dev-Build-v12-Build-#21 generated an exception
java.lang.NoClassDefFoundError: me/vagdedes/spartan/system/Enums$HackType
    at CrazyEnchantments[v1.8-Dev-Build-v12].jar//me.badbones69.premiumhooks.anticheat.SpartanSupport.cancelFastEat(SpartanSupport.java:22)
    at CrazyEnchantments[v1.8-Dev-Build-v12].jar//me.badbones69.crazyenchantments.processors.ArmorMoveProcessor.lambda$process$1(ArmorMoveProcessor.java:79)
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: me.vagdedes.spartan.system.Enums$HackType
    ... 10 more

**Comment by RyderBelserion** [comment]
[crazyenchantments.limit.#](https://github.com/Crazy-Crew/Crazy-Enchantments/releases/tag/1.9.1)
